stages:
  - build

before_script:
  - ruby --version
  - gem install cocoapods
  - gem install xcpretty
  - pod install

build_project:
  stage: build
  script:
    - xcodebuild -workspace CIDemo.xcworkspace -scheme CIDemo | xcpretty
    - xcodebuild test -workspace CIDemo.xcworkspace -scheme CIDemo -destination 'platform=iOS Simulator,name=iPhone 6s,OS=10.3' | xcpretty -s
  tags:
    - ios_10
    - xcode_8
