stages:
  - test

before_script:
  - ruby --version
  - gem install bundler
  - pod install

build_project:
  stage: test
  script:
    - xcodebuild test -workspace CIDemo.xcworkspace -scheme CIDemo -destination 'platform=iOS Simulator,name=iPhone 6s,OS=10.3' | xcpretty -s
  tags:
    - ios_10
    - xcode_8
