language: objective-c
xcode_workspace: CIDemo.xcworkspace
xcode_scheme: CIDemo
osx_image: xcode8.3
xcode_sdk: iphonesimulator10.3
before_script: bundle exec danger
before_install:
    - get install xcpretty -N --no-ri --no-rdoc
